# Generated by Django 2.2.10 on 2020-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200205_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='settings.MEDIA_ROOT/avatars/normal.png', upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
