# Generated by Django 2.2.10 on 2020-04-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bonuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuses',
            options={'ordering': ['date'], 'verbose_name': 'Бонусы', 'verbose_name_plural': 'Бонусы'},
        ),
    ]
