# Generated by Django 2.2.10 on 2020-04-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200414_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['user'], 'verbose_name': 'Доставку', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
