# Generated by Django 2.2.10 on 2020-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200307_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='Содержание статьи'),
        ),
    ]
