# Generated by Django 2.2.10 on 2020-03-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200307_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('body', models.TextField(max_length=300, verbose_name='содержимое')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Был добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Был изменен')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created'],
            },
        ),
    ]
