# Generated by Django 2.2.10 on 2020-03-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-added'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
