# Generated by Django 2.2.7 on 2019-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=400, verbose_name='Характеристики')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
                'ordering': ['price'],
            },
        ),
    ]
