# Generated by Django 2.2.6 on 2019-12-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191119_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Название'),
        ),
    ]
