# Generated by Django 2.2.6 on 2020-01-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200127_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
