# Generated by Django 2.2.6 on 2020-01-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200127_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
