# Generated by Django 2.2.10 on 2020-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200201_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/brand/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='settings.MEDIA_ROOT/images/large_technics-04-1_002.jpg', upload_to='images/'),
        ),
    ]
