# Generated by Django 2.2.10 on 2020-03-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0030_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Диагональ (дюйм)')),
                ('display_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(blank=True, max_length=10, null=True, verbose_name='Разрешение (пикс)')),
                ('processor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Процессор')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='Оперативная память')),
                ('storage', models.IntegerField(blank=True, null=True, verbose_name='Встроеная память (Гб)')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['product'],
            },
        ),
    ]
